### ISSUE TITLE
Feature in FeatureExtractorAccess not corresponding with implemented features

### ISSUE THREAD

**Issue by dinamix** [DDMAL/jSymbolic2#2]
Need to make sure that all the features implemented in jSymbolic2 are in fact referenced appropriately in FeatureExtractorAccess.

**Comment by codaich** [comment]
Details: Only 148 features are populated in the featureutils.FeatureExtractorAccess class, yet there are 158 features in the features package (and at least 153 specified in my dissertation, plus your two new MEI features).

**Comment by codaich** [comment]
When this is done, must also double check that feature appears once and only once in GUI feature table (and in the features extracted via the command line).

**Comment by codaich** [comment]
In a related note, MinorMajorTriadRatioFeature should be removed, as it was replaced by the combination of FractionOfMajorVerticalIntervalsFeature and FractionOfMinorVerticalIntervalsFeature.

**Comment by codaich** [comment]
Once this is done, should also verify that default features (i.e. with no config file specified) extracted are the same for both the GUI and the command line. (I believe that both interfaces reference the same point in the code, so this shouldn't be a problem, but I want to make sure).

**Comment by codaich** [comment]
I'll take this over, as it's related to other issues I'm working on.

**Comment by codaich** [comment]
Fixed in Commit 1fa0a08. Issue closed.
