### ISSUE TITLE
jMei2Midi is not detecting time signatures in MEI files and placing them in the converted MIDI

### ISSUE THREAD

**Issue by codaich** [DDMAL/jSymbolic2#29]
For example, for Mozart_Quintett_2013.mei MIDIInterMediateRepresentations.generateOverallMetadata() never receives a MetaMessage of type 0x58, despite the fact that the MEI file has a scoreDef tag that sets meter.count="3" meter.unit="4".

**Comment by codaich** [comment]
Also double check that jMei2Midi is actually encoding other relevant metadata in the MIDI files it generates in a way that jSymbolic can detece (time signature is the only one I've fully checked so far).

**Comment by dinamix** [comment]
http://www.recordingblogs.com/sa/Wiki/topic/MIDI-Time-Signature-meta-message

I'm using the above as a reference for MIDI time signatures. I was wondering if using 0xFF for the metronome byte (sixth byte) is adequate? The PPQ used in jMei2Midi is 256, so this would mean about one metronome tick per quarter by default.

**Comment by dinamix** [comment]
Also, it might be worthwhile to make this an issue in the jMei2Midi repository.

**Comment by codaich** [comment]
Good question. I think you are probably right, but I'm not 100% sure, so I suggest experimenting: make some MEI files of your own with different time signatures and tempii, extract features from them, and see if it works. You may need to consider what the tempo is, which is set by a set tempo message (http://www.recordingblogs.com/sa/Wiki/topic/MIDI-Set-Tempo-meta-message). Let me know if you get stuck or have problems.

**Comment by codaich** [comment]
And feel free to add this as an issue in the jMei2Midi repo, as you suggest.

**Comment by dinamix** [comment]
Fixed this together with the same issue in jMei2Midi

**Comment by codaich** [comment]
Great, please push related changes in jSymbolic2 (if any) and update the Third-Party-Jars repo to reflect the changes to jMei2Midi.

**Comment by dinamix** [comment]
Fixed by latest commits in jMei2Midi master branch

**Comment by codaich** [comment]
Good, confirmed fixed in jMei2Midi commit [8dfe0c4]. Issue closed.
