### ISSUE TITLE
Config file specifying input/output files does not extract features from all files

### ISSUE THREAD

**Issue by codaich** [DDMAL/jSymbolic2#5]
If a configuration file is used from the command line interface, and the config file specifies specific input paths and specific output paths, then only the features are actually saved from the first input file. No features are saved for any other files (the command line reports a "java.io.IOException: Stream Closed- Stream Closed" error, but continues processing).

This problem does not occur if a configuration file does not specify the files to process, and this information is provided at the command line.

**Comment by codaich** [comment]
As a side note, is there not supposed to be a list created of all files that fail processing?

**Comment by dinamix** [comment]
Closed it by mistake. Will wait on your confirmation.

**Comment by codaich** [comment]
Good, fixed in Commit [0168da6]. Issue closed.
